apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: addon-framework-iunq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: addon-framework-iunq
    app.kubernetes.io/part-of: mce-24
  name: addon-framework-iunq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: addon-framework-iunq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: addon-framework-iunq
    spec:
      containers:
      - image: image
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 1
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
