apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: addon-framework-iunq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: addon-framework-iunq
    app.kubernetes.io/part-of: mce-24
  name: addon-framework-iunq
spec:
  ports:
  - port: 1
    targetPort: 1
  selector:
    app.kubernetes.io/instance: addon-framework-iunq
status:
  loadBalancer: {}
