apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: discovery-testserver
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: discovery-testserver
    app.kubernetes.io/part-of: mce-24
  name: discovery-testserver
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: discovery-testserver
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: discovery-testserver
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/mce-24/discovery-testserver@sha256:81cab72f5f3468d406b8e54f5f00c6ea35d5b143ef18f831f17fd910cdbe6bbc
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
