apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: discovery-testserver
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: discovery-testserver
    app.kubernetes.io/part-of: mce-24
  name: discovery-testserver
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: discovery-testserver
status:
  loadBalancer: {}
