apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: registration-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: registration-operator
    app.kubernetes.io/part-of: mce-24
  name: registration-operator
spec:
  ports:
  - port: 1
    targetPort: 1
  selector:
    app.kubernetes.io/instance: registration-operator
status:
  loadBalancer: {}
