apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: provider-credential-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: provider-credential-controller
    app.kubernetes.io/part-of: mce-24
  name: provider-credential-contrztyv
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: provider-credential-controller
    weight: null
status: {}
