apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: foundation-e2e
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: foundation-e2e
    app.kubernetes.io/part-of: mce-24
  name: foundation-e2e
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: foundation-e2e
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: foundation-e2e
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/mce-24/foundation-e2e@sha256:f12b757c4748d8c1914c7ca452b575349839a9cf6b71f938bf01d0e60503f29a
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
