apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: foundation-e2e
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: foundation-e2e
    app.kubernetes.io/part-of: mce-24
  name: foundation-e2e
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: foundation-e2e
status:
  loadBalancer: {}
