apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: clusterlifecycle-state-metrics-1tww
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/mce-24/clusterlifecycle-state-metrics-1tww@sha256:747bc517435cb27f9d013dcec97a68b6248823ebb0c188b1ade14443ba3054e0
        name: my-go
        resources: {}
status: {}
