apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: cluster-curator-controller-2kgj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cluster-curator-controller-2kgj
    app.kubernetes.io/part-of: mce-24
  name: cluster-curator-controller-2kgj
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: cluster-curator-controller-2kgj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: cluster-curator-controller-2kgj
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/mce-24/cluster-curator-controller-2kgj@sha256:1be17389e5a7eabcbeab8ec52c4f57d362e50836014721e1a6d0f2a33576353f
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
