apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: clusterlifecycle-state-metrics-1tww
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterlifecycle-state-metrics-1tww
    app.kubernetes.io/part-of: mce-24
  name: clusterlifecycle-state-metrics-1tww
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: clusterlifecycle-state-metrics-1tww
status:
  loadBalancer: {}
