apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: cluster-image-set-controller-pbpe
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cluster-image-set-controller-pbpe
    app.kubernetes.io/part-of: mce-24
  name: cluster-image-set-controller-pbpe
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: cluster-image-set-controller-pbpe
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: cluster-image-set-controller-pbpe
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/mce-24/cluster-image-set-controller-pbpe@sha256:189db84a033cfd60e8023f52f2aefa958ed9ec25f2211ebb4555c53b92fc3959
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
