apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: registration-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: registration-operator
    app.kubernetes.io/part-of: mce-24
  name: registration-operatoremc5
spec:
  path: /
  port:
    targetPort: 1
  to:
    kind: Service
    name: registration-operator
    weight: null
status: {}
