apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: addon-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: addon-manager
    app.kubernetes.io/part-of: mce-24
  name: addon-manager
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: addon-manager
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: addon-manager
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/mce-24/addon-manager@sha256:2880582f2fa0fb90949b0800156068877bf81080847cf5d728d80ff018589796
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 1
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
