apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: registration
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: registration
    app.kubernetes.io/part-of: mce-24
  name: registration
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: registration
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: registration
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/mce-24/registration@sha256:be8f219caac49d130b2679a51088efaa0c08d618ecb21f2a00b96f0193203953
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 1
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
