apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: registration
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: registration
    app.kubernetes.io/part-of: mce-24
  name: registration
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: registration
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: registration
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/mce-24/registration@sha256:d0f04575bb6746d8a651bd6178729db40cf55a44e7524cf6c52270e0d2e00ab6
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 1
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
