apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: registration
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/mce-24/registration@sha256:d0f04575bb6746d8a651bd6178729db40cf55a44e7524cf6c52270e0d2e00ab6
        name: my-go
        resources: {}
status: {}
