apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: backplane-must-gather
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/mce-24/backplane-must-gather@sha256:53f3474f7b4a0ac45ea901c9c1fc88deda19ebd7f02cd3de928af0daf445620b
        name: container-image
        resources: {}
status: {}
