apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: kube-rbac-proxy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kube-rbac-proxy
    app.kubernetes.io/part-of: mce-24
  name: kube-rbac-proxy
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: kube-rbac-proxy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: kube-rbac-proxy
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/mce-24/kube-rbac-proxy@sha256:c8c27ed35ea7415b2270ed8b831216abd517f5cde339aea2172db0c547129e06
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
