apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: kube-rbac-proxy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kube-rbac-proxy
    app.kubernetes.io/part-of: mce-24
  name: kube-rbac-proxy
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: kube-rbac-proxy
status:
  loadBalancer: {}
