apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: helloprow-go-wcoc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: helloprow-go-wcoc
    app.kubernetes.io/part-of: mce-24
  name: helloprow-go-wcoc
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: helloprow-go-wcoc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: helloprow-go-wcoc
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/mce-24/helloprow-go-wcoc@sha256:f8870dad84bade6abf879b1c2bb8e091602a92d9a068d34c681004a12507288a
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 4321
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
