apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: helloprow-go-wcoc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: helloprow-go-wcoc
    app.kubernetes.io/part-of: mce-24
  name: helloprow-go-wcoc
spec:
  ports:
  - port: 4321
    targetPort: 4321
  selector:
    app.kubernetes.io/instance: helloprow-go-wcoc
status:
  loadBalancer: {}
