apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: cluster-proxy-plyk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cluster-proxy-plyk
    app.kubernetes.io/part-of: mce-24
  name: cluster-proxy-plyk
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: cluster-proxy-plyk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: cluster-proxy-plyk
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/mce-24/cluster-proxy-plyk@sha256:cae1541fc40fb54eda41df9c57182b4874aee2740ff72f2934c80aaf3a72a4a5
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
