apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hypershift-addon-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hypershift-addon-operator
    app.kubernetes.io/part-of: mce-24
  name: hypershift-addon-operator
spec:
  ports:
  - port: 2
    targetPort: 2
  selector:
    app.kubernetes.io/instance: hypershift-addon-operator
status:
  loadBalancer: {}
