apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hypershift-release-414
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hypershift-release-414
    app.kubernetes.io/part-of: mce-24
  name: hypershift-release-414
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: hypershift-release-414
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: hypershift-release-414
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/mce-24/hypershift-release-414@sha256:b4ee30fad0416f549beb731c80773f9a5ee916a048b0fa85e663b249b6ae76e7
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 9090
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
