apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hypershift-release-414
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/mce-24/hypershift-release-414@sha256:58601c868aa1078f4a048526a88825b74a022a56c9c1243cdae0924ddaf70e2d
        name: container-image
        resources: {}
status: {}
