apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: clusterclaims-controller-crbt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterclaims-controller-crbt
    app.kubernetes.io/part-of: mce-24
  name: clusterclaims-controller-crbt
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: clusterclaims-controller-crbt
    weight: null
status: {}
