apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: cluster-proxy-addon-ezmt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cluster-proxy-addon-ezmt
    app.kubernetes.io/part-of: mce-24
  name: cluster-proxy-addon-ezmt
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: cluster-proxy-addon-ezmt
    weight: 100
status: {}
