apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: cluster-proxy-addon-ezmt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cluster-proxy-addon-ezmt
    app.kubernetes.io/part-of: mce-24
  name: cluster-proxy-addon-ezmt
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: cluster-proxy-addon-ezmt
status:
  loadBalancer: {}
