apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: aws-encryption-provider-master
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: aws-encryption-provider-master
    app.kubernetes.io/part-of: mce-24
  name: aws-encryption-provider-master
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: aws-encryption-provider-master
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: aws-encryption-provider-master
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/mce-24/aws-encryption-provider-master@sha256:a0aa851192c087f522a885374e156a404cc0064de95225bcd849d451c55df19c
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
