apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: placement
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: placement
    app.kubernetes.io/part-of: mce-24
  name: placement
spec:
  port:
    targetPort: 1
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: placement
    weight: 100
status: {}
