apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: discovery-operator-tests
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: discovery-operator-tests
    app.kubernetes.io/part-of: mce-24
  name: discovery-operator-tests
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: discovery-operator-tests
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: discovery-operator-tests
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/mce-24/discovery-operator-tests@sha256:fe38061a6413a83c8eff02917c01c647f18fca5748ad6281dc3aaaadf54353f5
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
