apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: discovery-operator-tests
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: discovery-operator-tests
    app.kubernetes.io/part-of: mce-24
  name: discovery-operator-tests
spec:
  port:
    targetPort: 3000
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: discovery-operator-tests
    weight: 100
status: {}
