apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: managed-serviceaccount-zbkr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: managed-serviceaccount-zbkr
    app.kubernetes.io/part-of: mce-24
  name: managed-serviceaccount-zbkr
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: managed-serviceaccount-zbkr
status:
  loadBalancer: {}
