apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: managed-serviceaccount-zbkr
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/mce-24/managed-serviceaccount-zbkr@sha256:71b93fabc035f90be51c427238eff9fcfdbd199808a46dc88b903e3d8f946799
        name: container-image
        resources: {}
status: {}
