apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: backplane-operator-qa7p
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: backplane-operator-qa7p
    app.kubernetes.io/part-of: mce-24
  name: backplane-operator-qa7p
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: backplane-operator-qa7p
    weight: 100
status: {}
