apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: cluster-image-set-controller-pbpe
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cluster-image-set-controller-pbpe
    app.kubernetes.io/part-of: mce-24
  name: cluster-image-set-control3jmm
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: cluster-image-set-controller-pbpe
    weight: 100
status: {}
